import argparse
import asyncio
import json
from pathlib import Path

from app.retrieval.json_store import JsonVectorStore


async def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Input JSON file generated by export_index.py")
    parser.add_argument("--index-path", default=None, help="Optional JSON index path")
    parser.add_argument("--replace", action="store_true", help="Replace the current index")
    args = parser.parse_args()

    payload = json.loads(Path(args.input).read_text(encoding="utf-8"))
    rows = payload.get("chunks", [])
    store = JsonVectorStore(Path(args.index_path) if args.index_path else None)
    imported = await store.import_chunks(rows, replace=args.replace)
    print(json.dumps({"imported": imported, "replace": args.replace}, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
